package HospitalProject.utils;


import HospitalProject.service.GroupIncidenceService;
import HospitalProject.service.InformService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.stereotype.Component;

//This class will be used ONLY TO TESTING

@Component
public class RunnerFillingDB implements ApplicationRunner {


    //used to populate the DB when the app starts
    //this metod will be usefull to populate the databases of
    //HealthStaff and Pacient, but not Inform because Inform
    //will be generated by the user
    //@Autowired
    //InformService informService;

    @Autowired
    GroupIncidenceService groupIncidenceService;


    @Override
    public void run(ApplicationArguments args) throws Exception {

        //informService.populate();
        groupIncidenceService.populate();
    }


}
